"""overhauled the db and added more tables

Revision ID: 021fc32810ee
Revises: 5853da1a751d
Create Date: 2023-11-14 19:40:57.406045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '021fc32810ee'
down_revision: Union[str, None] = '5853da1a751d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('organization',
    # sa.Column('organization_id', sa.Integer(), nullable=False),
    # sa.Column('name', sa.String(length=255), nullable=False),
    # sa.Column('display_name', sa.String(length=255), nullable=True),
    # sa.Column('owner_id', sa.Integer(), nullable=False),
    # sa.Column('upldate', sa.DateTime(), nullable=False),
    # sa.Column('moddate', sa.DateTime(), nullable=False),
    # # sa.ForeignKeyConstraint(['owner_id'], ['trainer_profile.trainer_profile_id'], ),
    # sa.PrimaryKeyConstraint('organization_id')
    # )
    # op.create_table('trainer_profile',
    # sa.Column('trainer_profile_id', sa.Integer(), nullable=False),
    # sa.Column('override_display_name', sa.String(length=255), nullable=True),
    # sa.Column('user_id', sa.Integer(), nullable=False),
    # sa.Column('organization_id', sa.Integer(), nullable=False),
    # sa.Column('upldate', sa.DateTime(), nullable=False),
    # sa.Column('moddate', sa.DateTime(), nullable=False),
    # # sa.ForeignKeyConstraint(['organization_id'], ['organization.organization_id'], ),
    # sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    # sa.PrimaryKeyConstraint('trainer_profile_id')
    # )
    # op.create_table('user_report',
    # sa.Column('user_report_id', sa.Integer(), nullable=False),
    # sa.Column('schema_type', sa.String(length=255), nullable=False),
    # sa.Column('report_data', sa.String(length=255), nullable=False),
    # sa.Column('upldate', sa.DateTime(), nullable=False),
    # sa.Column('moddate', sa.DateTime(), nullable=False),
    # sa.PrimaryKeyConstraint('user_report_id')
    # )
    # op.create_table('workout_session',
    # sa.Column('workout_session_id', sa.Integer(), nullable=False),
    # sa.Column('upldate', sa.DateTime(), nullable=False),
    # sa.Column('moddate', sa.DateTime(), nullable=False),
    # sa.PrimaryKeyConstraint('workout_session_id')
    # )
    # op.create_table('workout_set',
    # sa.Column('workout_set_id', sa.Integer(), nullable=False),
    # sa.Column('upldate', sa.DateTime(), nullable=False),
    # sa.Column('moddate', sa.DateTime(), nullable=False),
    # sa.PrimaryKeyConstraint('workout_set_id')
    # )
    # op.create_table('exercise',
    # sa.Column('exercise_id', sa.Integer(), nullable=False),
    # sa.Column('name', sa.String(length=255), nullable=False),
    # sa.Column('target_muscles_json', sa.Text(), nullable=True),
    # sa.Column('user_id', sa.Integer(), nullable=False),
    # sa.Column('upldate', sa.DateTime(), nullable=False),
    # sa.Column('moddate', sa.DateTime(), nullable=False),
    # sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    # sa.PrimaryKeyConstraint('exercise_id')
    # )
    # op.add_column('user_demographic', sa.Column('height_inch', sa.Integer(), nullable=True))
    # op.add_column('user_demographic', sa.Column('weight_gram', sa.Integer(), nullable=True))
    # op.drop_column('user_demographic', 'height')
    # op.drop_column('user_demographic', 'weight')
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('user_demographic', sa.Column('weight', mysql.INTEGER(), autoincrement=False, nullable=True))
    # op.add_column('user_demographic', sa.Column('height', mysql.INTEGER(), autoincrement=False, nullable=True))
    # op.drop_column('user_demographic', 'weight_gram')
    # op.drop_column('user_demographic', 'height_inch')
    # op.drop_table('exercise')
    # op.drop_table('workout_set')
    # op.drop_table('workout_session')
    # op.drop_table('user_report')
    # op.drop_table('trainer_profile')
    # op.drop_table('organization')
    # ### end Alembic commands ###
