"""completely_recreating_tables2

Revision ID: 0d2082a125b8
Revises: 7abda6ff6577
Create Date: 2023-12-27 20:37:31.205622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d2082a125b8'
down_revision: Union[str, None] = '7abda6ff6577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainer_profile',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('override_display_name', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    # sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('upldate', sa.DateTime(), nullable=False),
    sa.Column('moddate', sa.DateTime(), nullable=False),
    # sa.ForeignKeyConstraint(['organization_id'], ['organization._id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )





    op.create_table('organization',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('upldate', sa.DateTime(), nullable=False),
    sa.Column('moddate', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['trainer_profile._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )

    op.create_table('user_report',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('schema_type', sa.String(length=255), nullable=False),
    sa.Column('report_data', sa.String(length=255), nullable=False),
    sa.Column('upldate', sa.DateTime(), nullable=False),
    sa.Column('moddate', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('workout_session',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('upldate', sa.DateTime(), nullable=False),
    sa.Column('moddate', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('workout_set',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('upldate', sa.DateTime(), nullable=False),
    sa.Column('moddate', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('exercise',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('target_muscles_json', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('upldate', sa.DateTime(), nullable=False),
    sa.Column('moddate', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('user_demographic',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('height_inch', sa.Integer(), nullable=True),
    sa.Column('weight_gram', sa.Integer(), nullable=True),
    sa.Column('activity_level', sa.Integer(), nullable=True),
    sa.Column('goal', sa.Integer(), nullable=True),
    sa.Column('weight_goal', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('upldate', sa.DateTime(), nullable=False),
    sa.Column('moddate', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_demographic')
    op.drop_table('exercise')
    op.drop_table('workout_set')
    op.drop_table('workout_session')
    op.drop_table('user_report')
    op.drop_table('trainer_profile')
    op.drop_table('organization')
    # ### end Alembic commands ###
