"""renamed primary key columns

Revision ID: 139e272cd86e
Revises: fdb506138ee5
Create Date: 2023-11-15 00:55:55.996659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '139e272cd86e'
down_revision: Union[str, None] = 'fdb506138ee5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass
    # op.drop_table('exercise')
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('exercise_ibfk_1', 'exercise', type_='foreignkey')
    # op.drop_constraint('trainer_profile_ibfk_1', 'trainer_profile', type_='foreignkey')
    # op.drop_constraint('user_demographic_ibfk_1', 'user_demographic', type_='foreignkey')
    
    # op.drop_column('exercise', 'exercise_id')
    # op.drop_column('organization', 'organization_id')
    # op.drop_column('trainer_profile', 'trainer_profile_id')
    # op.drop_column('user', 'user_id')
    # op.drop_column('user_demographic', 'user_demographic_id')
    # op.drop_column('user_report', 'user_report_id')
    # op.drop_column('workout_session', 'workout_session_id')
    # op.drop_column('workout_set', 'workout_set_id')
    
    # op.add_column('exercise', sa.Column('_id', sa.Integer(), nullable=False))
    # op.add_column('organization', sa.Column('_id', sa.Integer(), nullable=False))
    # op.add_column('trainer_profile', sa.Column('_id', sa.Integer(), nullable=False))
    # op.add_column('user', sa.Column('_id', sa.Integer(), nullable=False))
    # op.add_column('user_demographic', sa.Column('_id', sa.Integer(), nullable=False))
    # op.add_column('user_report', sa.Column('_id', sa.Integer(), nullable=False))
    # op.add_column('workout_session', sa.Column('_id', sa.Integer(), nullable=False))
    # op.add_column('workout_set', sa.Column('_id', sa.Integer(), nullable=False))

    # op.create_foreign_key(None, 'exercise', 'user', ['user_id'], ['_id'])
    # op.create_foreign_key(None, 'organization', 'trainer_profile', ['owner_id'], ['_id'])
    # op.create_foreign_key(None, 'trainer_profile', 'organization', ['organization_id'], ['_id'])
    # op.create_foreign_key(None, 'trainer_profile', 'user', ['user_id'], ['_id'])
    # op.create_foreign_key(None, 'user_demographic', 'user', ['user_id'], ['_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('workout_set', sa.Column('workout_set_id', mysql.INTEGER(), autoincrement=True, nullable=False))
    # op.drop_column('workout_set', '_id')
    # op.add_column('workout_session', sa.Column('workout_session_id', mysql.INTEGER(), autoincrement=True, nullable=False))
    # op.drop_column('workout_session', '_id')
    # op.add_column('user_report', sa.Column('user_report_id', mysql.INTEGER(), autoincrement=True, nullable=False))
    # op.drop_column('user_report', '_id')
    # op.add_column('user_demographic', sa.Column('user_demographic_id', mysql.INTEGER(), autoincrement=True, nullable=False))
    # op.drop_constraint(None, 'user_demographic', type_='foreignkey')
    # op.create_foreign_key('user_demographic_ibfk_1', 'user_demographic', 'user', ['user_id'], ['user_id'])
    # op.drop_column('user_demographic', '_id')
    # op.add_column('user', sa.Column('user_id', mysql.INTEGER(), autoincrement=True, nullable=False))
    # op.drop_column('user', '_id')
    # op.add_column('trainer_profile', sa.Column('trainer_profile_id', mysql.INTEGER(), autoincrement=True, nullable=False))
    # op.drop_constraint(None, 'trainer_profile', type_='foreignkey')
    # op.drop_constraint(None, 'trainer_profile', type_='foreignkey')
    # op.create_foreign_key('trainer_profile_ibfk_1', 'trainer_profile', 'user', ['user_id'], ['user_id'])
    # op.drop_column('trainer_profile', '_id')
    # op.add_column('organization', sa.Column('organization_id', mysql.INTEGER(), autoincrement=True, nullable=False))
    # op.drop_constraint(None, 'organization', type_='foreignkey')
    # op.drop_column('organization', '_id')
    # op.add_column('exercise', sa.Column('exercise_id', mysql.INTEGER(), autoincrement=True, nullable=False))
    # op.drop_constraint(None, 'exercise', type_='foreignkey')
    # op.create_foreign_key('exercise_ibfk_1', 'exercise', 'user', ['user_id'], ['user_id'])
    # op.drop_column('exercise', '_id')
    # # ### end Alembic commands ###
