"""add_user_demographic2
Revision ID: 1b5cf9947382
Revises: a7a9ac5251df
Create Date: 2023-08-22 21:40:01.752742
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b5cf9947382'
down_revision: Union[str, None] = 'a7a9ac5251df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_demographic',
    sa.Column('user_demographic_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('activity_level', sa.Integer(), nullable=True),
    sa.Column('goal', sa.Integer(), nullable=True),
    sa.Column('weight_goal', sa.Integer(), nullable=True),
    sa.Column('upldate', sa.DateTime(), nullable=False),
    sa.Column('moddate', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_demographic_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_demographic')
    # ### end Alembic commands ###
