"""changed relationship between organization and user

Revision ID: 2b7a47c239bd
Revises: f44c372edfbf
Create Date: 2023-12-31 01:44:38.573918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2b7a47c239bd'
down_revision: Union[str, None] = 'f44c372edfbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('organization_ibfk_1', 'organization', type_='foreignkey')
    op.create_foreign_key(None, 'organization', 'user', ['owner_xid'], ['xid'])
    op.add_column('trainer_profile', sa.Column('user_xid', sa.Integer(), nullable=False))
    op.drop_constraint('trainer_profile_ibfk_1', 'trainer_profile', type_='foreignkey')
    op.create_foreign_key(None, 'trainer_profile', 'user', ['user_xid'], ['xid'])
    op.drop_column('trainer_profile', 'userxid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainer_profile', sa.Column('userxid', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'trainer_profile', type_='foreignkey')
    op.create_foreign_key('trainer_profile_ibfk_1', 'trainer_profile', 'user', ['userxid'], ['xid'])
    op.drop_column('trainer_profile', 'user_xid')
    op.drop_constraint(None, 'organization', type_='foreignkey')
    op.create_foreign_key('organization_ibfk_1', 'organization', 'trainer_profile', ['owner_xid'], ['xid'])
    # ### end Alembic commands ###
