"""fix reference to userxid in exercise table

Revision ID: 35981566c2fc
Revises: 02c83f611a18
Create Date: 2024-12-09 23:20:19.899261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '35981566c2fc'
down_revision: Union[str, None] = '02c83f611a18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('user_xid', sa.Integer(), nullable=False))
    op.drop_constraint('exercise_ibfk_1', 'exercise', type_='foreignkey')
    op.create_foreign_key(None, 'exercise', 'user', ['user_xid'], ['xid'])
    op.drop_column('exercise', 'userxid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('userxid', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'exercise', type_='foreignkey')
    op.create_foreign_key('exercise_ibfk_1', 'exercise', 'user', ['userxid'], ['xid'])
    op.drop_column('exercise', 'user_xid')
    # ### end Alembic commands ###
