"""Add Constraint Unique User Demographic user_id

Revision ID: 5853da1a751d
Revises: 1b5cf9947382
Create Date: 2023-09-03 21:10:20.965971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5853da1a751d'
down_revision: Union[str, None] = '1b5cf9947382'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_demographic', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_demographic', type_='unique')
    # ### end Alembic commands ###
