"""add common_muscle_group_target to exercise

Revision ID: 6bf96b1f0b8b
Revises: 1dcff654a634
Create Date: 2025-04-11 14:50:21.424241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bf96b1f0b8b'
down_revision: Union[str, None] = '1dcff654a634'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('common_muscle_group_target', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise', 'common_muscle_group_target')
    # ### end Alembic commands ###
