"""adding user_xid to workout_session

Revision ID: 6fb1e3ae69d7
Revises: bb953fa1d464
Create Date: 2024-12-12 14:29:58.065428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fb1e3ae69d7'
down_revision: Union[str, None] = 'bb953fa1d464'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_session', sa.Column('user_xid', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'workout_session', 'user', ['user_xid'], ['xid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workout_session', type_='foreignkey')
    op.drop_column('workout_session', 'user_xid')
    # ### end Alembic commands ###
