"""Making certain fields nullable for user

Revision ID: 9e9b35ea97d7
Revises: 6fb1e3ae69d7
Create Date: 2025-04-02 17:43:19.121035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9e9b35ea97d7'
down_revision: Union[str, None] = '6fb1e3ae69d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_verified', sa.Boolean(), nullable=False))
    op.alter_column('user', 'first_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)
    op.alter_column('user', 'first_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('user', 'email_verified')
    # ### end Alembic commands ###
