"""add deleted column to exercise

Revision ID: a36f712f68e9
Revises: 35981566c2fc
Create Date: 2024-12-11 12:05:25.009198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a36f712f68e9'
down_revision: Union[str, None] = '35981566c2fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('deleted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise', 'deleted')
    # ### end Alembic commands ###
