"""adding columns to workout session

Revision ID: bb953fa1d464
Revises: d9dabc3efba5
Create Date: 2024-12-12 14:11:33.784234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb953fa1d464'
down_revision: Union[str, None] = 'd9dabc3efba5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_session', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('workout_session', sa.Column('start_time_utc', sa.DateTime(), nullable=True))
    op.add_column('workout_session', sa.Column('end_time_utc', sa.DateTime(), nullable=True))
    op.add_column('workout_session', sa.Column('deleted_utc', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_session', 'deleted_utc')
    op.drop_column('workout_session', 'end_time_utc')
    op.drop_column('workout_session', 'start_time_utc')
    op.drop_column('workout_session', 'name')
    # ### end Alembic commands ###
