"""add workout routine exercise relationship table

Revision ID: c7edafc074c2
Revises: e49efbdec0f0
Create Date: 2025-04-15 10:16:25.558440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7edafc074c2'
down_revision: Union[str, None] = 'e49efbdec0f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_routine_exercise_relationship',
    sa.Column('xid', sa.Integer(), nullable=False),
    sa.Column('workout_routine_xid', sa.Integer(), nullable=False),
    sa.Column('exercise_xid', sa.Integer(), nullable=False),
    sa.Column('upldate', sa.DateTime(), nullable=False),
    sa.Column('moddate', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_xid'], ['exercise.xid'], ),
    sa.ForeignKeyConstraint(['workout_routine_xid'], ['workout_routine.xid'], ),
    sa.PrimaryKeyConstraint('xid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_routine_exercise_relationship')
    # ### end Alembic commands ###
