"""rest day bool to workout routine

Revision ID: cfe2d6f67451
Revises: c7edafc074c2
Create Date: 2025-04-15 13:47:38.954894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfe2d6f67451'
down_revision: Union[str, None] = 'c7edafc074c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_routine', sa.Column('is_rest_day', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_routine', 'is_rest_day')
    # ### end Alembic commands ###
