"""add deleted column to exercise, make it not nullable

Revision ID: d9dabc3efba5
Revises: a36f712f68e9
Create Date: 2024-12-11 13:46:07.175414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd9dabc3efba5'
down_revision: Union[str, None] = 'a36f712f68e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('exercise', 'deleted',
    #            existing_type=mysql.DATETIME(),
    #            nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('exercise', 'deleted',
    #            existing_type=mysql.DATETIME(),
    #            nullable=True)
    # ### end Alembic commands ###
