"""add workout routine table

Revision ID: e49efbdec0f0
Revises: 6bf96b1f0b8b
Create Date: 2025-04-15 10:11:09.541543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e49efbdec0f0'
down_revision: Union[str, None] = '6bf96b1f0b8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_routine',
    sa.Column('xid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('user_xid', sa.Integer(), nullable=False),
    sa.Column('upldate', sa.DateTime(), nullable=False),
    sa.Column('moddate', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_xid'], ['user.xid'], ),
    sa.PrimaryKeyConstraint('xid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_routine')
    # ### end Alembic commands ###
