"""changed id names to xid

Revision ID: eef885996062
Revises: 0d2082a125b8
Create Date: 2023-12-30 20:40:59.014365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eef885996062'
down_revision: Union[str, None] = '0d2082a125b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('xid', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=500), nullable=False),
    sa.Column('upldate', sa.DateTime(), nullable=False),
    sa.Column('moddate', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('xid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_report',
    sa.Column('xid', sa.Integer(), nullable=False),
    sa.Column('schema_type', sa.String(length=255), nullable=False),
    sa.Column('report_data', sa.String(length=255), nullable=False),
    sa.Column('upldate', sa.DateTime(), nullable=False),
    sa.Column('moddate', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('xid')
    )
    op.create_table('workout_session',
    sa.Column('xid', sa.Integer(), nullable=False),
    sa.Column('upldate', sa.DateTime(), nullable=False),
    sa.Column('moddate', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('xid')
    )
    op.create_table('workout_set',
    sa.Column('xid', sa.Integer(), nullable=False),
    sa.Column('upldate', sa.DateTime(), nullable=False),
    sa.Column('moddate', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('xid')
    )
    op.create_table('exercise',
    sa.Column('xid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('target_muscles_json', sa.Text(), nullable=True),
    sa.Column('userxid', sa.Integer(), nullable=False),
    sa.Column('upldate', sa.DateTime(), nullable=False),
    sa.Column('moddate', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userxid'], ['user.xid'], ),
    sa.PrimaryKeyConstraint('xid')
    )
    op.create_table('trainer_profile',
    sa.Column('xid', sa.Integer(), nullable=False),
    sa.Column('override_display_name', sa.String(length=255), nullable=True),
    sa.Column('userxid', sa.Integer(), nullable=False),
    sa.Column('upldate', sa.DateTime(), nullable=False),
    sa.Column('moddate', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userxid'], ['user.xid'], ),
    sa.PrimaryKeyConstraint('xid')
    )
    op.create_table('user_demographic',
    sa.Column('xid', sa.Integer(), nullable=False),
    sa.Column('height_inch', sa.Integer(), nullable=True),
    sa.Column('weight_gram', sa.Integer(), nullable=True),
    sa.Column('activity_level', sa.Integer(), nullable=True),
    sa.Column('goal', sa.Integer(), nullable=True),
    sa.Column('weight_goal', sa.Integer(), nullable=True),
    sa.Column('userxid', sa.Integer(), nullable=False),
    sa.Column('upldate', sa.DateTime(), nullable=False),
    sa.Column('moddate', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userxid'], ['user.xid'], ),
    sa.PrimaryKeyConstraint('xid')
    )
    op.create_table('organization',
    sa.Column('xid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('ownerxid', sa.Integer(), nullable=False),
    sa.Column('upldate', sa.DateTime(), nullable=False),
    sa.Column('moddate', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ownerxid'], ['trainer_profile.xid'], ),
    sa.PrimaryKeyConstraint('xid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization')
    op.drop_table('user_demographic')
    op.drop_table('trainer_profile')
    op.drop_table('exercise')
    op.drop_table('workout_set')
    op.drop_table('workout_session')
    op.drop_table('user_report')
    op.drop_table('user')
    # ### end Alembic commands ###
