"""fixed name of ownerxid to owner_xid

Revision ID: f44c372edfbf
Revises: eef885996062
Create Date: 2023-12-30 21:37:49.146057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f44c372edfbf'
down_revision: Union[str, None] = 'eef885996062'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('owner_xid', sa.Integer(), nullable=False))
    op.drop_constraint('organization_ibfk_1', 'organization', type_='foreignkey')
    op.create_foreign_key(None, 'organization', 'trainer_profile', ['owner_xid'], ['xid'])
    op.drop_column('organization', 'ownerxid')
    op.add_column('user_demographic', sa.Column('user_xid', sa.Integer(), nullable=False))
    op.drop_constraint('user_demographic_ibfk_1', 'user_demographic', type_='foreignkey')
    op.create_foreign_key(None, 'user_demographic', 'user', ['user_xid'], ['xid'])
    op.drop_column('user_demographic', 'userxid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_demographic', sa.Column('userxid', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_demographic', type_='foreignkey')
    op.create_foreign_key('user_demographic_ibfk_1', 'user_demographic', 'user', ['userxid'], ['xid'])
    op.drop_column('user_demographic', 'user_xid')
    op.add_column('organization', sa.Column('ownerxid', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'organization', type_='foreignkey')
    op.create_foreign_key('organization_ibfk_1', 'organization', 'trainer_profile', ['ownerxid'], ['xid'])
    op.drop_column('organization', 'owner_xid')
    # ### end Alembic commands ###
